sudo: false
language: node_js
node_js:
  - '7'

script:
  - npm run build

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key:
      secure: zjAzKZDDjEpaQCpS389xEAxH7DsPbPMlIErSw8zb6XT8OzJ5C/RfTYpW51+SszHDVmVsBArsV3TPqygpzL9zEhQRrIdhW8sjeim3om3Zpbq8mFpC2/T/L6jsuZXT0lTuEImFEsxH6MUguW1HlSW2BjoWaB/Jrghn3WNDpkygqIq14MGSPWDe2iqXTbBV6w/2Xia8Ms43wTKHDfXFZC54KTldeWz/+Jw6OB5lJR+ZsiUp3WZUzoc75kspC/TeAzDi8+MHJVVtjoNfbRPXNcQD6tZaaELroDv9dmcwYZt7EybNx9oxNaLsgHjkQBwgynlI/HtsjBPYyn7/oEdOVlvqyuznkCMEwwvQkLgsp7FkGu7pHJNKT23ninxsArSOygzPjwSvDAqGCVxYtUJNe6MrOGOqmDUYiIxQxzv6/SQUAM16mMZ5L/TY/yAINsIS9l+MVWa6NuCpfUca1gvRtF5DH6lE4s3c/JWDxJa3Ywdw4H2+hkj7bNGTAr2/uqqVo+R1V4mG8PcfZ2nt99xn13nm9Jhv799sZqWyuYfphcmgwN0rDjVVMGRtXBtokonGkVDRq9y2aJfEr2685oTsCR37DTSFqGqgCNErKKncRvz4vtyxduGVkPQ55O3Fs2ZoYt221BVZwLUnM+kE2k2f/Ns9262uHuuq+mtizjdJuRbgt1E=
    on:
      branch: master
      tags: true
      repo: tourstream/tstr-booking-manager-connector
  - provider: gcs
    skip_cleanup: true
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_ACCESS_SECRET
    bucket: $GCS_BUCKET
    acl: public-read
    local-dir: dist-master
    on:
      branch: master
      repo: tourstream/tstr-booking-manager-connector
  - provider: gcs
    skip_cleanup: true
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_ACCESS_SECRET
    bucket: $GCS_BUCKET
    acl: public-read
    local-dir: dist-version
    on:
      tags: true
      repo: tourstream/tstr-booking-manager-connector
