sudo: false
language: node_js
node_js:
  - '8'

script:
  - npm run build
  - npm run test

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key:
      secure: $NPM_TOURSTREAM-EU_TOKEN
    on:
      branch: master
      tags: true
      repo: tourstream/tstr-booking-manager-connector
  - provider: gcs
    skip_cleanup: true
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_ACCESS_SECRET
    bucket: $GCS_BUCKET
    acl: public-read
    local-dir: dist-master
    on:
      branch: master
      repo: tourstream/tstr-booking-manager-connector
  - provider: gcs
    skip_cleanup: true
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_ACCESS_SECRET
    bucket: $GCS_BUCKET
    acl: public-read
    local-dir: dist-version
    on:
      tags: true
      repo: tourstream/tstr-booking-manager-connector
